name: Deploy website
on:
  push:
    branches:
      - dev
jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build project (static)
        run: npm run build
        working-directory: ./frontend
        env:
          NITRO_PRESET: static
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_site }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.ftp_path }}
          local-dir: ./frontend/.output/public/